Updated previous PR to adjust MetaAndAssetCtxs method
hyperliquid-dex/hyperliquid-python-sdk pull request #20
Opened 2024-02-24 14:08 UTC by zknpr

updated  the MetaAndAssetCtxs method from [previous PR](https://github.com/hyperliquid-dex/hyperliquid-python-sdk/pull/12)

2024-02-27 16:53 UTC, lmlmt requested changes

2024-02-27 16:53 UTC, lmlmt commented on hyperliquid/info.py
> +        def metaAndAssetCtxs(self) -> MetaAndAssetCtxs:
please fix indentation here

2024-02-27 16:53 UTC, lmlmt commented on hyperliquid/utils/types.py
> +        "impactPxs":Union
fix formatting

2024-05-18 17:50 UTC, bernatfp commented
Would be great to get this merged!

2024-07-04 14:25 UTC, zknpr commented
I’m closing this PR because the reviewer is not reviewing it.

2024-07-04 14:25 UTC, closed without merging