#55 Vault usd transfer
hyperliquid-dex/hyperliquid-python-sdk pull request #56
Opened 2024-09-23 16:41 UTC by cgaspart

Use the SDK to deposit USD in a vault

2024-09-25 22:56 UTC, traderben requested changes
Thanks for creating this PR. Overall looks good, just a couple of small comments

2024-09-25 22:56 UTC, traderben commented on examples/basic_vault_transfer.py
> +    if exchange.account_address != exchange.wallet.address:
remove this, agents are allowed to perform vault transfers

2024-09-25 22:56 UTC, traderben commented on examples/basic_vault_transfer.py
> +    transfer_result = exchange.vault_usd_transfer("0xa15099a30bbf2e68942d6f4c43d70d04faeab0a0", True, 5000000)
nit
```suggestion
    transfer_result = exchange.vault_usd_transfer("0xa15099a30bbf2e68942d6f4c43d70d04faeab0a0", True, 5_000_000)
```

2024-09-25 22:56 UTC, traderben commented on examples/basic_vault_transfer.py
> +    transfer_result = exchange.vault_usd_transfer("0xa15099a30bbf2e68942d6f4c43d70d04faeab0a0", True, 5000000)
Also, can you select the hlp address based on if exchange is mainnet vs. testnet (or add a comment to change it if using a different environment)

2024-09-26 09:14 UTC, cgaspart commented
@traderben I edited the exemple as requested.
Also I created a new variable that refer to the HLP vault so that's more explicit.

2024-09-26 16:19 UTC, traderben approved these changes

2024-09-26 16:19 UTC, merged