Improve code documentation and add comments for clarity
hyperliquid-dex/hyperliquid-python-sdk pull request #83
Opened 2024-12-22 13:23 UTC by patidarrahul

- Enhanced the comments and documentation throughout the code.
- Clarified agent creation and order management logic.
- Added comments explaining security considerations, order placement, and cancellation processes.
- Improved readability for future developers and maintainers.

2025-01-17 00:29 UTC, traderben requested changes

2025-01-17 00:29 UTC, traderben commented on examples/basic_agent.py
> +    # Setting up the environment (exchange, account info, etc.) for testing purposes.
Prefer present tense here and throughout
```suggestion
    # Set up the environment (exchange, account info, etc.) for testing purposes.
```

2025-01-17 00:29 UTC, traderben commented on examples/basic_agent.py
> +    # This prevents the risk of accidentally creating an agent using the wallet itself, which could compromise funds.
This will not compromise funds. It should just fail as an Agent does not have permission to approve agents

2025-02-05 19:09 UTC, patidarrahul commented on examples/basic_agent.py
> +    # This prevents the risk of accidentally creating an agent using the wallet itself, which could compromise funds.
Makes sense. Have made the change.

2025-02-05 19:10 UTC, patidarrahul commented on examples/basic_agent.py
> +    # Setting up the environment (exchange, account info, etc.) for testing purposes.
I have looked at it the whole file again and made one more change.

2025-02-05 19:40 UTC, traderben approved these changes

2025-02-05 19:40 UTC, traderben commented
LGTM, thanks for the additional comments

2025-02-05 19:40 UTC, merged