Docstring additon
hyperliquid-dex/hyperliquid-python-sdk pull request #90
Opened 2024-12-29 00:29 UTC by rustyresearch

Added spot user state docstring to info.py

2024-12-29 01:31 UTC, rustyresearch commented
Added historial orders

2025-01-01 10:41 UTC, rustyresearch commented
Adds support for the `aggregateByTime` parameter to the fills endpoints in the Info class. When enabled, this aggregates partial fills that occur when a crossing order gets filled by multiple resting orders.

## Changes
- Added `aggregate_by_time` optional parameter to `user_fills()`
- Added `aggregate_by_time` optional parameter to `user_fills_by_time()`
- Updated docstrings with new parameter details and response format

## Why
The Hyperliquid API supports fill aggregation but this wasn't exposed in the SDK. This is useful for analysis tools that want to see consolidated fills rather than individual partial fills.

## Example
# Get aggregated fills
fills = info.user_fills(address, aggregate_by_time=True)

# Get aggregated fills in time range
fills = info.user_fills_by_time(
    address, 
    start_time, 
    end_time, 
    aggregate_by_time=True
)

2025-01-17 00:52 UTC, traderben requested changes

2025-01-17 00:52 UTC, traderben commented on hyperliquid/info.py
> +        req = {"type": "userFills", "user": address}
is there an issue with always setting the optional values? This is causing a type error:
hyperliquid/info.py:217:38: error: Incompatible types in assignment (expression has type "bool", target has type "str")

2025-01-17 00:52 UTC, traderben commented on hyperliquid/info.py
> +        req = {"type": "userFillsByTime", "user": address, "startTime": start_time}
ditto

2025-02-01 00:44 UTC, rustyresearch commented
- Only add aggregate_by_time to the request in user_fills if provided.
- Only add end_time to the request in user_fills_by_time if provided.

This prevents sending None values and avoids type errors.

2025-02-15 09:56 UTC, closed without merging